<?php $gridrecords = $block->getDetails(); ?>
    <div class="table-wrapper orders-history">

<!--        Tabel-->
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('Entity Id') ?></th>
                <th scope="col" class="col title"><?php echo __('Name') ?></th>
                <th scope="col" class="col product"><?php echo __('Gender') ?></th>
                <th scope="col" class="col amount"><?php echo __('Dob') ?></th>
                <th scope="col" class="col amount"><?php echo __('Action') ?></th>
            </tr>
            </thead>
            <tbody>

                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Entity Id')) ?>" class="col id">
                        <?php echo $gridrecords->getId() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col id">
                        <?php echo $gridrecords->getName() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Gender')) ?>" class="col id">
                        <?php if($gridrecords->getGender()==1){
                            echo "Nam";
                        }else{
                            echo "Nữ";
                        } ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Dob')) ?>" class="col id">
                        <?php echo $gridrecords->getDob() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Detail')) ?>" class="col id" name="id">
                        <a name="id" href="<?php echo $block->getUrl('student/student/details/') ?>">Detail</a>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>

